// Generated by scripts/sync-release-notes.mjs. Do not edit manually.
import type { ReleaseNotesContent } from "./types"

export const currentReleaseNotes = {
  version: "1.1.6",
  date: "2026-07-16",
  notes: {
    en: "### ✨ Improvements\n\n- **Claude page structure adaptation** — Adapted to Claude's updated conversation page DOM, ensuring the outline can read all messages and conversation exports remain complete. (#781)\n\n### 🐛 Bug Fixes\n\n- **Claude Canvas document export** — Fixed issue where Markdown and clipboard exports could omit Claude Canvas document content; exports now collect Canvas documents from the conversation, including virtualized messages, and restore the previously open Canvas afterward.\n- **Claude Canvas Smart Avoidance** — Fixed issue where opening a Claude Canvas document could stop Smart Avoidance from reserving space for the Ophel panel, causing the document content to be covered.\n- **Global shortcut URL** — Fixed issue where the global shortcut continued to open Gemini after setting a custom URL. (#778)",
    zh: "### ✨ 功能优化\n\n- **Claude 页面结构适配** — 适配 Claude 更新后的对话页面 DOM 结构，确保大纲能够读取全部消息，并完整导出会话内容。(#781)\n\n### 🐛 问题修复\n\n- **Claude Canvas 文档导出** — 修复 Markdown 和剪贴板导出可能遗漏 Claude Canvas 文档正文的问题；现在会收集会话中的 Canvas 文档（包括虚拟列表中的文档），并在导出后恢复原先打开的 Canvas。\n- **Claude Canvas 智能避让** — 修复打开 Claude Canvas 文档后，智能避让可能无法继续为 Ophel 面板预留空间，导致文档内容被遮挡的问题。\n- **全局快捷键打开网址** — 修复自定义全局快捷键打开 URL 后，快捷键仍会打开 Gemini 默认地址的问题。(#778)",
  },
  fullChangelogUrls: {
    en: "https://ophel.app/docs/changelog",
    zh: "https://ophel.app/docs/zh/changelog",
  },
  media: [],
} as const satisfies ReleaseNotesContent
