// Generated by scripts/sync-release-notes.mjs. Do not edit manually.
import type { ReleaseNotesContent } from "./types"

export const currentReleaseNotes = {
  version: "1.1.7",
  date: "2026-07-22",
  notes: {
    en: "### ✨ Improvements\n\n- **Reading history restoration controls** — Automatic reading-position restoration now yields immediately when scrolling or selecting an outline item, so user navigation always takes priority and the selected position is preserved. (#797)\n\n### 🐛 Bug Fixes\n\n- **Claude outline refresh after replies** — Fixed issue where sending a new message in a previously indexed long Claude conversation could restart the full outline scan and scroll through the conversation again; new replies now update the cached outline incrementally. (#785)\n- **Claude outline current-position highlight** — Fixed issue where the outline could highlight an earlier question when the visible Claude question began with the same text; current-position tracking now follows the exact question at that conversation position.",
    zh: "### ✨ 功能优化\n\n- **阅读历史恢复控制** — 自动恢复阅读位置时，现在滚动正文或选择大纲条目会立即停止恢复，让用户导航始终优先，并保存用户选择的新位置。(#797)\n\n### 🐛 问题修复\n\n- **Claude 回复后的大纲刷新** — 修复已完成索引的 Claude 长对话在发送新问题后会重新全量扫描并滚动整段会话的问题；新回复现在只会增量更新已有大纲缓存。(#785)\n- **Claude 大纲当前位置高亮** — 修复当前可见问题与前文问题使用相同开头时，大纲可能高亮到前一个问题的问题；当前位置跟随现在会准确对应当前问题。",
  },
  fullChangelogUrls: {
    en: "https://ophel.app/docs/changelog",
    zh: "https://ophel.app/docs/zh/changelog",
  },
  media: [],
} as const satisfies ReleaseNotesContent
